image: node:15.0.0

pipelines:
  pull-requests:
      '**':
        - step:
            caches:
              - node
            name: InstallNodeModules
            script:
              - npm install
        - parallel: 
            - step:
                name: LintTest
                script:
                  - npm install
                  - npm run lint 
            - step:
                name: FormatCheck
                script:
                  - npm install
                  - npm run lint                  
            - step:
                name: ImportSortCheck
                script:
                  - npm install
                  - npm run import-sort:check  
            - step:
                name: CspellCheck
                script:
                  - npm install
                  - npm cspell:check